name: MyChunkPlus
main: me.lucasemanuel.mychunkplus.Main
version: 1.4
depend: [MyChunk, WorldGuard]

permissions:
  mychunkplus.override:
    description: Allows a user to build on unowned chunks.
    default: op